-- =====================================================
-- QUICK INSERT: 20 Diseases
-- Copy and paste this into phpMyAdmin SQL tab
-- =====================================================

INSERT INTO `diseases` (`id`, `name`, `category`, `severity`, `emoji`, `description`, `symptoms`, `causes`, `prevention`, `treatment`, `affected_population`, `duration`) VALUES
('disease-001', 'Common Cold', 'Infectious', 'Mild', '🤧', 'A viral infection of the upper respiratory tract.', '["Runny nose", "Sneezing", "Cough", "Sore throat", "Mild fever", "Headache"]', '["Rhinovirus", "Coronavirus", "Contact with infected person"]', '["Wash hands frequently", "Avoid close contact", "Cover mouth when coughing"]', '["Rest", "Drink fluids", "Over-the-counter medicine"]', 'All age groups', '7-10 days'),
('disease-002', 'Influenza (Flu)', 'Infectious', 'Moderate', '🤒', 'A contagious respiratory illness.', '["Fever", "Chills", "Muscle aches", "Fatigue", "Cough"]', '["Influenza virus", "Airborne droplets"]', '["Annual flu vaccination", "Wash hands", "Avoid sick people"]', '["Antiviral medications", "Rest", "Fluids"]', 'All age groups', '1-2 weeks'),
('disease-003', 'COVID-19', 'Infectious', 'Severe', '🦠', 'A respiratory illness caused by SARS-CoV-2.', '["Fever", "Cough", "Shortness of breath", "Loss of taste/smell"]', '["SARS-CoV-2 virus", "Close contact"]', '["Vaccination", "Wear masks", "Social distancing"]', '["Rest", "Isolation", "Medical help if severe"]', 'All age groups', '1-3 weeks'),
('disease-004', 'Chickenpox', 'Infectious', 'Moderate', '🦠', 'A highly contagious viral infection.', '["Itchy rash", "Fever", "Blisters", "Fatigue"]', '["Varicella-zoster virus", "Direct contact"]', '["Vaccination", "Avoid contact", "Good hygiene"]', '["Rest", "Calamine lotion", "Antihistamines"]', 'Children', '10-21 days'),
('disease-005', 'Measles', 'Infectious', 'Severe', '🌡️', 'A highly contagious viral disease.', '["High fever", "Cough", "Rash", "Red eyes"]', '["Measles virus", "Airborne"]', '["MMR vaccination", "Isolation"]', '["Rest", "Fluids", "Medical supervision"]', 'Unvaccinated individuals', '7-14 days'),
('disease-006', 'Diabetes Type 2', 'Chronic', 'Severe', '🍬', 'A chronic condition affecting blood sugar.', '["Increased thirst", "Frequent urination", "Fatigue"]', '["Obesity", "Family history", "Lack of exercise"]', '["Maintain weight", "Exercise", "Balanced diet"]', '["Medication", "Insulin", "Diet management"]', 'Adults over 45', 'Lifelong'),
('disease-007', 'Hypertension', 'Chronic', 'Moderate', '❤️', 'High blood pressure condition.', '["Headaches", "Dizziness", "Chest pain"]', '["Age", "Obesity", "High salt intake"]', '["Exercise", "Reduce salt", "Healthy diet"]', '["Medication", "Lifestyle changes"]', 'Adults over 40', 'Lifelong'),
('disease-008', 'Asthma', 'Respiratory', 'Moderate', '🌬️', 'Chronic respiratory condition.', '["Wheezing", "Shortness of breath", "Coughing"]', '["Allergies", "Air pollution", "Genetics"]', '["Avoid triggers", "Use inhaler", "Manage allergies"]', '["Inhalers", "Medications", "Avoid triggers"]', 'All age groups', 'Lifelong'),
('disease-009', 'Bronchitis', 'Respiratory', 'Moderate', '😷', 'Inflammation of bronchial tubes.', '["Persistent cough", "Mucus", "Fatigue"]', '["Viral infections", "Smoking", "Air pollution"]', '["Avoid smoking", "Wash hands", "Get vaccinated"]', '["Rest", "Fluids", "Cough medicine"]', 'All age groups', '1-3 weeks'),
('disease-010', 'Pneumonia', 'Respiratory', 'Severe', '🫁', 'Infection inflaming air sacs in lungs.', '["Chest pain", "Cough", "Fever", "Shortness of breath"]', '["Bacteria", "Viruses", "Weakened immune system"]', '["Vaccination", "Wash hands", "Healthy lifestyle"]', '["Antibiotics", "Rest", "Oxygen therapy"]', 'Elderly and children', '1-3 weeks'),
('disease-011', 'Gastroenteritis', 'Digestive', 'Moderate', '🤢', 'Inflammation of stomach and intestines.', '["Diarrhea", "Nausea", "Vomiting", "Abdominal cramps"]', '["Viruses", "Bacteria", "Contaminated food"]', '["Wash hands", "Cook food thoroughly"]', '["Rest", "Stay hydrated", "Oral rehydration"]', 'All age groups', '1-3 days'),
('disease-012', 'Irritable Bowel Syndrome', 'Digestive', 'Moderate', '💊', 'Disorder affecting the large intestine.', '["Abdominal pain", "Bloating", "Diarrhea", "Constipation"]', '["Food sensitivities", "Stress", "Hormonal changes"]', '["Identify triggers", "Manage stress", "Exercise"]', '["Diet modifications", "Medications", "Probiotics"]', 'Adults, especially women', 'Chronic'),
('disease-013', 'Eczema', 'Skin', 'Moderate', '🔴', 'Condition making skin red and itchy.', '["Itchy skin", "Red patches", "Dry skin"]', '["Genetics", "Allergens", "Stress"]', '["Moisturize", "Avoid triggers", "Gentle soaps"]', '["Topical creams", "Antihistamines", "Moisturizers"]', 'All age groups', 'Chronic'),
('disease-014', 'Psoriasis', 'Skin', 'Moderate', '🔴', 'Skin disease causing red scaly patches.', '["Red patches", "Silvery scales", "Itching"]', '["Genetics", "Immune system", "Stress"]', '["Moisturize", "Avoid triggers", "Sun exposure"]', '["Topical treatments", "Light therapy", "Medications"]', 'Adults 15-35', 'Chronic'),
('disease-015', 'Depression', 'Mental Health', 'Severe', '😔', 'Mood disorder causing persistent sadness.', '["Persistent sadness", "Loss of interest", "Fatigue"]', '["Genetics", "Brain chemistry", "Life events"]', '["Exercise", "Healthy diet", "Social support"]', '["Therapy", "Medications", "Support groups"]', 'All age groups', 'Varies'),
('disease-016', 'Anxiety Disorder', 'Mental Health', 'Moderate', '😰', 'Excessive worry interfering with daily life.', '["Excessive worry", "Restlessness", "Fatigue"]', '["Genetics", "Personality", "Trauma"]', '["Stress management", "Exercise", "Adequate sleep"]', '["Therapy", "Medications", "Mindfulness"]', 'All age groups', 'Varies'),
('disease-017', 'Migraine', 'Neurological', 'Moderate', '🤕', 'Neurological condition with intense headaches.', '["Severe headache", "Nausea", "Sensitivity to light"]', '["Genetics", "Hormonal changes", "Stress"]', '["Identify triggers", "Regular sleep", "Manage stress"]', '["Pain relievers", "Triptans", "Rest"]', 'Adults, especially women', '4-72 hours'),
('disease-018', 'Epilepsy', 'Neurological', 'Severe', '🧠', 'Neurological disorder with recurrent seizures.', '["Seizures", "Confusion", "Loss of consciousness"]', '["Genetics", "Brain injury", "Infections"]', '["Take medications", "Adequate sleep", "Avoid triggers"]', '["Antiepileptic medications", "Surgery", "Lifestyle"]', 'All age groups', 'Lifelong'),
('disease-019', 'Conjunctivitis', 'Eye', 'Mild', '👁️', 'Inflammation of the outer eye membrane.', '["Red eyes", "Itching", "Tearing", "Discharge"]', '["Bacteria", "Viruses", "Allergies"]', '["Wash hands", "Avoid touching eyes", "Don't share towels"]', '["Antibiotic drops", "Antihistamines", "Warm compresses"]', 'All age groups', '1-2 weeks'),
('disease-020', 'Cataracts', 'Eye', 'Moderate', '👁️', 'Clouding of the eye lens.', '["Cloudy vision", "Blurred vision", "Difficulty at night"]', '["Aging", "Diabetes", "UV exposure"]', '["Wear sunglasses", "Quit smoking", "Manage diabetes"]', '["Surgery", "New eyeglasses", "Brighter lighting"]', 'Elderly over 60', 'Progressive');

SELECT '20 diseases inserted successfully!' AS message;

